### ISSUE TITLE
[Issue] SysTray & Focused Monitor

### ISSUE THREAD

**Issue by linuxmobile** [garado/cozy#8]
Good morning, my good friend Garado. I have tested the current configuration, and I am very happy with everything you have done! I wanted to say that I find two small issues. 

- There is no systray, so you can't display apps like discord, telegram, spotify, etc.
- The widgets open on the second monitor, and not on the main monitor, although a better solution, would be to have them open on the monitor where the cursor is!

**Comment by garado** [comment]
Thanks for the bug report! I usually only use 1 monitor and I don't need a systray so I didn't notice these.

Widgets now open on the focused screen, and here are the systray updates:
- option to enable/disable systray (check `cozyconf/default.lua`)
- optional open/close animation (animations enabled by default - check `cozyconf/default.lua`)
- toggle-able by clicking the toggle icon on the bar or with a keybind (alt + s by default)
- on opening, it will show on the focused screen (it can't be on all screens because of some x11 specification)
- a few tiny bugs that I couldn't figure out how to fix but overall I think it works well.

The code was written for 1 monitor so there will be some random bugs still with multi-monitor setups, but I will get around to those :-)

new submodules have been added so `git pull --recurse-submodules`, and don't forget to update your cozyconf with the 2 new options
